### ISSUE TITLE
secret.json이 필요합니다.

### ISSUE THREAD

**Issue by olgi3rd** [milooy/smart-shopping-cart#40]

**Comment by milooy** [comment]
olgierd.everac@gmail.com 메일로 보냈습니다 ^^ 고맙습니다

**Comment by olgi3rd** [comment]
@milooy 감사합니다. 디자인이 멋지네요.

**Comment by olgi3rd** [comment]
@milooy 어떤 식으로 해야 될까요? Chrome extension도 필요한가요?

**Comment by milooy** [comment]
@olgierd-on-fire 크롬 확장 플러그인 세팅에 들어가서 `extension`폴더를 '압축해제된 확장 플러그인 로드'에 넣어주시면 됩니다.
![image](https://cloud.githubusercontent.com/assets/3839771/18824712/1f0dccd2-83ff-11e6-9eb7-116ff153313b.png)

**Comment by milooy** [comment]
현재 크롬 익스텐션에선 제품 이름/썸네일만 크롤링해오고있고,
TODO는
- 장고 User model과 계정 연동
- 쇼핑몰 사이트에서 범용적으로 가격 크롤링하는 알고리즘

등이 있습니다.

**Comment by olgi3rd** [comment]
@milooy 아, 이미 프로젝트 디렉토리에 있었군요. 감사합니다. 👍
